### PR TITLE
[security] yarn upgrade

### PR DESCRIPTION
**Pull request by marcdumais-work**
Also updated to a later lerna and ovsx devDendencies.

In a second commit, I remove lerna and add the couple
of devDependencies that were missing.

`yarn audit`:
before:
17 vulnerabilities found - Packages audited: 418
Severity: 7 Moderate | 10 High

_after:_
_0 vulnerabilities found - Packages audited: 716_
__after - updated after lerna removal__
__0 vulnerabilities found - Packages audited: 169__

Signed-off-by: Marc Dumais <marc.dumais@ericsson.com>

<a href="https://gitpod.io/#https://github.com/eclipse-theia/vscode-builtin-extensions/pull/92"></a>

### CODE REVIEW

**Review by vince-fugnitto — APPROVED** [review]
The changes look good to me :+1: 

I confirmed that:
- [x] building and publishing works successfully
- [x] `yarn audit` produces no known vulnerabilities

**Comment by marcdumais-work** [comment]
@vince-fugnitto I removed lerna in a second commit - thanks for the suggestion!

**Review by vince-fugnitto — APPROVED** [review]
@marcdumais-work the changes look good to me, I've also cleaned up a bit further my removing references of lerna in the documentation https://github.com/eclipse-theia/vscode-builtin-extensions/pull/92/commits/d99080b67c8036eaa1657d5f6dbb070db3bf28c3.

**Comment by marcdumais-work** [comment]
> I've also cleaned up a bit further my removing references of lerna in the documentation [

Thanks!

**Pull request merged**
