### PR TITLE
fix packaging issues on Windows

### PR DESCRIPTION
**Pull request by paul-marechal**
Tweak the scripts to allow building and packaging from Windows.

Use `execa` instead of `child_process` to spawn subprocesses as it
behaves better when invoking things like `yarn`.

Use `cross-env` to set environment variables in the npm scripts.

Update the types for `node` as we expect to run at least 14.

Cleanup some code.

<a href="https://gitpod.io/#https://github.com/eclipse-theia/vscode-builtin-extensions/pull/90"></a>

### CODE REVIEW

**Review by vince-fugnitto — APPROVED** [review]
The changes look good to me :+1: 
- [x] confirmed that there are no regressions - the repo builds and successfully packages
- [x] the new dependencies are licensed approved

**Review by marcdumais-work — APPROVED** [review]
LGTM - thanks Paul!

**Comment by CiciDongxue** [comment]
您好，我已收到您的来信，暂时无法回复您的邮件，望见谅。

**Comment by marcdumais-work** [comment]
To be able to test-run built-ins built with these changes, I think we should use the magic branch to publish a new `next` release, based on `1.53.2`, and then use that in e.g. Blueprint, etc.

**Comment by marcdumais-work** [comment]
> To be able to test-run built-ins built with these changes, I think we should use the magic branch to publish a new `next` release, based on `1.53.2`, and then use that in e.g. Blueprint, etc.

Attempt to publish a new `next`: 
https://github.com/eclipse-theia/vscode-builtin-extensions/actions/runs/1554761935

**Pull request merged**
