### PR TITLE
Changes for 1.83.1

### PR DESCRIPTION
**Pull request by tsmaeder**
Updated build environment

### CODE REVIEW

**Comment by tsmaeder** [comment]
@marcdumais-work not really clear to me how to test this locally and what the process for fixing problem should be.

**Comment by marcdumais-work** [comment]
Hi Thomas,

> @marcdumais-work not really clear to me how to test this locally

Did you see this? 
https://github.com/eclipse-theia/vscode-builtin-extensions/wiki/Produce-and-Publish-the-set-of-vscode-built-in-extensions#local-testing

> The only way to really test this seems to be to push a new ovsx-publsh branch. So "testing in production", so to speak.

For system-level testing, that's correct. For example, testing that Theia-based applications will pick the latest published built-ins vs the previous version. 

But it's at least possible to by-pass openvsx and test locally-produced builtins, to make sure that they load and seem to work correctly. Granted that last part is manual - you need to do operations that will trigger and exercise the main functionalities. I would do minimal testing of the following "main" or more substential built-in extensions: Typescript, git, HTML and JSON. 

The link above gives pointers to achieve that. 

> and what the process for fixing problem should be. 

It depends on what the problems are. For issues building the build-ins, you play "whack-a-mole" with issues until the build works. (Like you've done by stepping to node 18 and in this PR here). I would do this locally on my laptop and then attempt to update the workflows with my findings. 

Sometimes you might discover functional issues with your locally produced build-ins. E.g. that some APIs are missing or do not behave as expected by one or more built-in extension. In such cases, it may be necessary to fix the issue in Theia. If it's expected to take a while, you can pin the extension(s) by hardcoding the URL of the previous (well working) version in the `package.json` of the example application (this will serve as example for other Theia-based apps to do similar in their app if necessary).

**Review by marcdumais-work — APPROVED** [review]
LGTM. I briefly tried to locally build the built-ins with vscode baseline 1.83.1 and I got the same errors that are happening in the workflow execution. After I installed libkrb5-dev, the errors went away. I already had `libgbm1` installed.

**Comment by marcdumais-work** [comment]
@tsmaeder I think I understand your question better now that I know the nature of the issue you encountered. I think you have a Windows laptop, which makes it difficult for you to debug the build locally (they way Vince and I did). 

I think it would be good to have a workflow that builds PRs, but does not publish to openvsx. Workflow "publish-vsx-latest" was meant for something else - it will not use the vscode baseline but checkout the latest release of vscode, and so is not suitable for this (publish-vsx-next is similar but uses latest "next').

**Comment by marcdumais-work** [comment]
Oops - unresolvable conflict resulted - I have rolled-back and will propose the commit in a separate PR

**Pull request merged**
