### PR TITLE
gh-actions: update workflows to use node 12

### PR DESCRIPTION
**Pull request by vince-fugnitto**
Fixes: https://github.com/eclipse-theia/vscode-builtin-extensions/issues/57

<a href="https://gitpod.io/#https://github.com/eclipse-theia/vscode-builtin-extensions/pull/67"></a>

### CODE REVIEW

**Comment by vince-fugnitto** [comment]
I'm wondering as to why we use `node 10` in the workflows, I noticed that the build has been failing for some time:

image


```
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
error playwright@1.11.1: The engine "node" is incompatible with this module. Expected version ">=12". Got "10.24.1"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

**Review by alvsan09 — APPROVED** [review]
It looks good to me!.
I think it's best to merge it as soon as possible, so we can use it as a base to address additional issues.

Symbolically approving! :-)

**Comment by marcdumais-work** [comment]
@vince-fugnitto did you try building locally, to confirm everything works with node 12?

**Comment by marcdumais-work** [comment]
BTW, we need the libsecret fix for the Gitpod config, here in this repo too.

**Comment by marcdumais-work** [comment]
(thinking of it, I think I use node 12 when I build this repo locally, so it should work I think, if there are no other problems)

**Review by marcdumais-work — APPROVED** [review]
LGTM, thanks Vince!

**Comment by marcdumais-work** [comment]
Let's merge and see if it's sufficient  for CI to work again.

**Comment by marcdumais-work** [comment]
(you'll need to switch the PR from draft mode before we can merge)

**Pull request merged**
